name: Build app
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Generate new image tag
        run: |
          DATE=$(date +%y%m%d)
          COMMIT_SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG=master-${DATE}.${COMMIT_SHA}
          IMAGE_NAME="laposa/testflow:${IMAGE_TAG}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"
          echo "IMAGE_NAME=$IMAGE_NAME" >> "$GITHUB_ENV"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:app"
          push: true
          tags: |
            laposa/testflow:latest
            ${{ env.IMAGE_NAME }}
